# Generated by Django 5.0.4 on 2024-05-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='taskPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('All', 'ALL'), ('Done', 'DONE'), ('To-Do', 'TO DO'), ('In-Progress', 'IN PROGRESS')], default='To-Do', max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Task Details',
                'db_table': 'tbl_task',
            },
        ),
    ]
